### ISSUE TITLE
Add tracking of liquidity in pools over time

### ISSUE THREAD

**Issue by maht0rz** [galacticcouncil/Basilisk-api-old#7]
### Detailed Description
As a user, i want to be able to retrieve historical liquidity information about a given asset pair (pool), for both XYK & LBP pools. This will help subsequently calculate the historical spot price at the given time, using the already indexed liquidities of both assets in the pool.

### Context
For instance, on the UI we want to display a historical spot price graph, and knowing the liquidity in any given block in time is necessary in order to achieve that.

### Possible Implementation

Example, don't follow 1:1

```
type LiquidityOverTime {
// could be assetAID - assetBID
// where the order of assets is alphabetical in order to be deterministic from the client side
ID: ID!,
// actual liquidities / balances
assetA: BigInt!,
assetB: BigInt!
}
```

### Acceptance criteria

- [x] Integration tested with mocks/stubs at the handler level
- [x] Unit tested at function level

### Tasks

- [x] Analyse the implementation posibilities
- [x] Design schema
- [x] Implement handlers
- [x] Implement a custom time-based gql resolver, that will return a given number of entries that fit into a time constraint
    e.g. data for the past hour, but limited to only a 100 entries (parametrisable)
- [x] Write unit/integration tests

**Comment by maht0rz** [comment]
@enthusiastmartin will deal with the custom time-based gql resolver ^^

**Comment by dexterslabor** [comment]
Basilisk node needs to be at least at https://github.com/galacticcouncil/Basilisk-node/commit/56679ae004368db37f4430e3a60694b86a35ea11 because of https://github.com/galacticcouncil/Basilisk-node/issues/229.
